[project]
name = "sky-watch"
version = "0.1.0"
description = "Отслеживание самолётов в воздушном пространстве выбранных стран через nominatim и opensky-network"
authors = [
    {name = "mrMoish",email = "_@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "requests (>=2.34.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)"
]
